language: go

go:
  - 1.8

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - mkdir /home/travis/.contactkey
  - mv examples/config.sample.yml  /home/travis/.contactkey/config.yml
  - mkdir /tmp/manifests
  - mv examples/manifest.sample.yml /tmp/manifests/manifest.yml
  - ./hack/verify-gofmt.sh
  - go test --cover $(go list ./... | grep -v /vendor/)
  - go build -o cck
  - ./cck -h

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: cck
  skip_cleanup: true
  on:
    tags: true