language: go

go:
  - 1.8

install:
  - sudo apt-get install -y --force-yes upx
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - mkdir /home/travis/.contactkey
  - cp examples/config.sample.yml  /home/travis/.contactkey/config.yml
  - mkdir /tmp/manifests
  - cp examples/manifest.sample.yml /tmp/manifests/manifest.yml
  - ./hack/verify-gofmt.sh
  - go test --cover $(go list ./... | grep -v /vendor/)
  - go build -o /tmp/cck
  - /tmp/cck -h

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
