workPath: /tmp/manifests

globalEnvironments:
  - preprod

deployers:
  ggn:
    vcsRegexp: -v(.+)
    workPath: /tmp
    environments:
      preprod: pp

  k8s:
    vcsRegexp: -v(.+)
    workPath: /tmp
    environments:
      local:
        cluster: ops
      preprod:
        cluster: preprod

sources:
  stash:
    user:        user
    password:    password
    url:         url
    sha1MaxSize: 7

binaries:
  nexus:
    url:        127.0.0.1
    repository: repository
    group:      group

hooks:
  slack:
    url:   127.0.0.1
    token: token

metrics:
  prometheus:
    url: http://demo.robustperception.io:9091

lockSystem:
  fileLock:
    filePath: /tmp
